dist: trusty
language: c

before_install:
    - sudo apt-get install -y build-essential git 
    - git clone https://github.com/openssl/openssl.git && cd openssl && ./config && make -j2 && sudo make install >/dev/null 2>&1 && cd ..

script:
    - make all
    - make tests
