dist: trusty
language: c

before_install:
    - sudo apt-get install -y build-essential git 
    - git clone https://github.com/openssl/openssl.git && cd openssl && ./config && make && sudo make install

script: make tests
